name: NormalOresEarn
version: '1.0'
main: ru.normalwalk.normaloresearn.Main
api-version: '1.16'
depend: [Vault]
authors: [NormalWalk_ | vk.com/normalwalk | t.me/normalwalk]
description: Плагин на заработок денег добывая руды.
commands:
  normaloresearn: {}